src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/authorization/StudentLogin.java
package edu.iit.sat.itmd4515.abhimani.fp.domain.authorization;

import edu.iit.sat.itmd4515.abhimani.fp.EncryptText;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
@Entity
@Table(name="auth_students_login")
@NamedQueries({
    @NamedQuery(name="StudentLogin.authenticate", query="SELECT l FROM StudentLogin AS l WHERE l.Username=:uname AND l.Password IS NOT NULL")
})
public class StudentLogin
	implements Comparable<StudentLogin>, Serializable{
    //COLUMNS
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(nullable=false)
    protected long LoginID;

    @Column(length=255, unique=true, updatable=false)
    @Size(min=4)
    private String Username;

    @Column(name="enc_pwd", length=64)
    @Size(min=8, max=40)
    private String Password;

    //CONSTRUCT
    private StudentLogin(){
	super();
    }

    /**
     * You must not initialize and use an instance of this class with the
     * default constructor, instead use the Student.getAuth() and
     * Student.setAuth(StudentLogin auth) methods to access or update the
     * credentials; Use this constructor only to use the matchLogin(String
     * Password) and authenticate the user.
     *
     * @param Username Expects a Username to initialize the class
     */
    public StudentLogin(String Username){
	this.Username=Username.trim();
    }

    //PROPERTIES
    public long getLoginID(){
	return this.LoginID;
    }

    public String getUsername(){
	return this.Username;
    }

    public String getPasswordKey(){
	return this.Password;
    }

    /**
     * Password is sha256ed and saved.
     *
     */
    @PrePersist
    @PreUpdate
    private void cryptPassword(){
	this.Password=EncryptText.crypt(this.Password);
    }

    public void setPassword(String Password){
	this.Password=Password.trim();
    }

    /**
     * Can be used to authenticate the user.
     *
     *
     * @param Password Expects Student password for matching
     *
     * @return A Boolean True or False
     */
    public boolean matchLogin(String Password){
	return EncryptText.hashEquals(this.getPasswordKey(), Password);
    }

    //IMPLEMENTATION
    /**
     * CompareTo implemented on the Username of the Student which is unqiue.
     *
     * @param el Expects an element of type StudentLogin
     */
    @Override
    public int compareTo(StudentLogin el){
	return (this.getUsername().compareTo(el.getUsername()));
    }

    //OVERRIDES
    @Override
    public int hashCode(){
	return ((this.getLoginID()>0) ? Long.hashCode(this.getLoginID()) : 0);
    }

    @Override
    public boolean equals(Object el){
	if(!(el instanceof StudentLogin))
	    return false;
	try{
	    StudentLogin tstLogin=(StudentLogin)el;
	    if(!(Integer.compare(this.hashCode(), tstLogin.hashCode())==0))
		return false;
	}catch(Exception ex){
	    return false;
	}
	return true;
    }

    @Override
    public String toString(){
	try{
	    return ("NOT_AUTHORIZED");
	}catch(Exception ex){
	    return ex.toString();
	}
    }
}

src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/entities/Department.java
package edu.iit.sat.itmd4515.abhimani.fp.domain.entities;

import edu.iit.sat.itmd4515.abhimani.fp.domain.AbstractEntityUnit;
import edu.iit.sat.itmd4515.abhimani.fp.domain.relations.DepartmentOffice;
import java.io.Serializable;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
@Entity
@Table(name="departments")
@NamedQueries({
    @NamedQuery(name="Departments.retrieveAll", query="SELECT d FROM Department AS d"),
    @NamedQuery(name="Departments.findByID", query="SELECT d FROM Department AS d WHERE d.PID=:PID"),
    @NamedQuery(name="Departments.findByName", query="SELECT d FROM Department AS d WHERE d.Name=:Name")
})
public class Department
	extends AbstractEntityUnit
	implements Comparable<Department>, Serializable{
    //COLUMNS
    @Column(name="Dept_Name", nullable=false, length=255, unique=true)
    @Size(min=4)
    private String Name;

    @Column(name="Description", length=2000)
    private String Description;

    @OneToMany(cascade=CascadeType.REMOVE, mappedBy="Dept")
    private List<DepartmentOffice> lstOffices;

    @OneToMany(cascade=CascadeType.PERSIST, mappedBy="Dept")
    private List<Event> lstEvents;

    //CONSTRUCTS
    public Department(){
	super();
    }

    public Department(String Name, String Description){
	this.Name=Name.trim();
	this.Description=Description.trim();
    }

    public Department(String Name){
	this.Name=Name.trim();
    }

    //PROPERTIES
    public String getName(){
	return this.Name;
    }

    public void setName(String Name){
	this.Name=Name.trim();
    }

    public String getDescription(){
	return this.Description;
    }

    public void setDescription(String Description){
	this.Description=Description.trim();
    }

    //RELATIONS
    /**
     * Holds a list of offices that belong to the Department.
     *
     * @return Returns a list of Offices under the Department
     */
    public List<DepartmentOffice> getDepartmentOfficesList(){
	return lstOffices;
    }

    public void addDepartmentOffice(DepartmentOffice office){
	if(!this.getDepartmentOfficesList().contains(office))
	    this.lstOffices.add(office);
    }

    /**
     * Holds a list of events held by the department or will be held.
     *
     * @return Returns a list of Events held by the Department
     */
    public List<Event> getDepartmentEvents(){
	return lstEvents;
    }

    //IMPLEMENTATION
    /**
     * CompareTo implemented on the Name of the Department which is unqiue.
     *
     * @param el Expects an element of type Department
     */
    @Override
    public int compareTo(Department el){
	return (this.getName().compareTo(el.getName()));
    }

    //OVERRIDES
    @Override
    public boolean equals(Object el){
	if(!(el instanceof Department))
	    return false;
	try{
	    Department tstDept=(Department)el;
	    if(!(Integer.compare(this.hashCode(), tstDept.hashCode())==0))
		return false;
	}catch(Exception ex){
	    return false;
	}
	return true;
    }

    @Override
    public String toString(){
	try{
	    return ("/Entities.Department{ID:"+this.getPID()+", Name:\""+this.getName()+"\", Description:{Length:"+((this.getDescription()==null) ? 0 : this.getDescription().length())+"}, Offices:"+this.getDepartmentOfficesList().size()+", Events:"+this.getDepartmentEvents().size()+"}");
	}catch(Exception ex){
	    return ex.toString();
	}
    }
}

src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/entities/Event.java
package edu.iit.sat.itmd4515.abhimani.fp.domain.entities;

import edu.iit.sat.itmd4515.abhimani.fp.domain.AbstractEntityUnit;
import edu.iit.sat.itmd4515.abhimani.fp.domain.EventState;
import edu.iit.sat.itmd4515.abhimani.fp.domain.relations.Comment;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Future;
import javax.validation.constraints.Size;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
@Entity
@Table(name = "event_store")
@NamedQueries({
    @NamedQuery(name = "Events.retrieveAll", query = "SELECT e FROM Event AS e"),
    @NamedQuery(name = "Events.findByID", query = "SELECT e FROM Event AS e WHERE e.PID=:PID"),
    @NamedQuery(name = "Events.retrieveByDepartment", query = "SELECT e FROM Event AS e WHERE e.Dept=:Dept"),
    @NamedQuery(name = "Events.retrieveByVenue", query = "SELECT e FROM Event AS e WHERE e.Ven=:Ven")
})
public class Event
	extends AbstractEntityUnit
	implements Comparable<Event>, Serializable{
    //COLUMNS
    @Column(name = "Title", nullable = false, length = 255, unique = true)
    @Size(min = 4)
    private String Title;

    @Column(name = "Description", length = 2000)
    private String Description;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EBegin", nullable = false)
    @Future
    private Date EBegin;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EEnd", nullable = false)
    @Future
    private Date EEnd;

    @Column(name = "AState", nullable = false)
    private EventState AState=EventState.NEW;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CDate", nullable = false, insertable = true, updatable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private final Date CDate=new Date();

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MDate", insertable = false, updatable = true, columnDefinition = "TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
    private Date MDate;

    @JoinColumn(name = "Event_Dept_ID", referencedColumnName = "PID", nullable = false)
    @ManyToOne(optional = false)
    private Department Dept;

    @JoinColumn(name = "Event_Venue_ID", referencedColumnName = "PID", nullable = false)
    @ManyToOne(optional = false)
    private Venue Ven;

    @OneToMany(cascade = CascadeType.REMOVE, mappedBy = "Evt")
    private List<Comment> lstComments;

    @ManyToMany(mappedBy = "lstEvents")
    private List<Student> lstStudents=new ArrayList<>();

    //CONSTRUCTS
    public Event(){
	super();
    }

    public Event(Department Dept, Venue Ven, String Title, String Description, Date EBegin, Date EEnd, EventState AState){
	this.Dept=Dept;
	this.Ven=Ven;
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
	this.AState=AState;
    }

    public Event(Department Dept, Venue Ven, String Title, String Description, Date EBegin, Date EEnd){
	this.Dept=Dept;
	this.Ven=Ven;
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
    }

    public Event(String Title, String Description, Date EBegin, Date EEnd, EventState AState){
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
	this.AState=AState;
    }

    public Event(String Title, String Description, Date EBegin, Date EEnd){
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
    }

    //PROPERTIES
    public String getTitle(){
	return Title;
    }

    public void setTitle(String Title){
	this.Title=Title.trim();
    }

    public String getDescription(){
	return Description;
    }

    public void setDescription(String Description){
	this.Description=Description.trim();
    }

    public Date getRawEBegin(){
	return EBegin;
    }

    public String getEBegin(){
	return EBegin.toString();
    }

    public void setEBegin(Date EBegin){
	this.EBegin=EBegin;
    }

    public Date getRawEEnd(){
	return EEnd;
    }

    public String getEEnd(){
	return EEnd.toString();
    }

    public void setEEnd(Date EEnd){
	this.EEnd=EEnd;
    }

    public EventState getRawAState(){
	return AState;
    }

    public String getAState(){
	return AState.toString();
    }

    public void setAState(EventState AState){
	this.AState=AState;
    }

    /**
     * This field is inserted only once automatically upon row creation.
     *
     * @return Returns Creation Date
     */
    public String getCDate(){
	return CDate.toString();
    }

    /**
     * This field is updated automatically receives last update date.
     *
     * @return Returns Last Modified Date
     */
    public String getMDate(){
	return ((MDate==null) ? "-" : MDate.toString());
    }

    //RELATIONS
    public Department getDepartment(){
	return Dept;
    }

    public void setDepartment(Department Dept){
	this.Dept=Dept;
    }

    public Venue getVenue(){
	return Ven;
    }

    public void setVenue(Venue Ven){
	this.Ven=Ven;
    }

    public List<Student> getStudentList(){
	return lstStudents;
    }

    public void addStudent(Student stud){
	if(!this.getStudentList().contains(stud))
	    this.lstStudents.add(stud);
	if(!stud.getEventList().contains(this))
	    stud.attendEvent(this);
    }

    public void removeStudent(Student stud){
	if(this.getStudentList().contains(stud))
	    this.lstStudents.remove(stud);
	if(stud.getEventList().contains(this))
	    stud.unAttendEvent(this);
    }

    /**
     * Holds a list of comments received for the event.
     *
     * @return Returns a list of Comments from Students for the Event
     */
    public List<Comment> getComments(){
	return lstComments;
    }

    //IMPLEMENTATION
    /**
     * CompareTo implemented on the Title field.
     *
     * @param el Expects an element of type Event
     */
    @Override
    public int compareTo(Event el){
	return (this.getEBegin().compareTo(el.getEBegin()));
    }

    //OVERRIDES
    @Override
    public boolean equals(Object el){
	if(!(el instanceof Event))
	    return false;
	try{
	    Event tstEvt=(Event)el;
	    if(!(Integer.compare(this.hashCode(), tstEvt.hashCode())==0))
		return false;
	}catch(Exception ex){
	    return false;
	}
	return true;
    }

    @Override
    public String toString(){
	try{
	    return ("/Entities.Event{ID:"+this.getPID()+", Dept_ID:\""+this.getDepartment().getPID()+"\", Department:\""+this.getDepartment().getName()+"\", Venue_ID:\""+this.getVenue().getPID()+"\", Venue:\""+this.getVenue().getTitle()+"\", Title:\""+this.getTitle()+"\", Description:{Length:"+((this.getDescription()==null) ? 0 : this.getDescription().length())+"}, EBegin:\""+this.getEBegin()+"\", EEnd:\""+this.getEEnd()+"\", Comments:"+this.getComments().size()+", State:"+this.getAState().toUpperCase()+", Create_Date:\""+this.getCDate()+"\", Last_Modified:\""+this.getMDate()+"\"}");
	}catch(Exception ex){
	    return ex.toString();
	}
    }
}

src/main/webapp/Administrators/Departments/Manage_Department.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		   xmlns:h="http://java.sun.com/jsf/html"
		   xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
		   xmlns:f="http://java.sun.com/jsf/core"
		    template="./../../WEB-INF/abstracts/tplAdmin2.xhtml">
<ui:define name="cph_Title">New Venue</ui:define>

<ui:define name="cph_Heading">#{empty request.getParameter("department_id")? 'Create': 'Update'} Department</ui:define>

<ui:define name="cph_Content">
<h:form id="x0">
    <f:metadata>
	<f:viewParam name="department_id" value="#{controllerProcessDepartment.department_id}" />
	<f:viewAction action="#{controllerProcessDepartment.pre_load}" />
    </f:metadata>
<table id="tblx">
<tbody>
    <tr><td style="border-top:1px solid #bbb;"></td></tr>
     <tr>
	<td><label>
	    <span class="bold">Name</span> <span class="red">*</span><br />
	     <h:inputText id="txtName" title="Enter Name" p:placeholder="Enter Name" maxlength="155" alt="1" value="#{controllerProcessDepartment.strName}" />
	    </label>
	</td>
    </tr>
    <tr>
	<td><label>
	    <span class="bold">Description</span> <span class="red">*</span><br />
		<h:inputTextarea p:placeholder="Enter Description" id="txtDescription" style="width:300px;height:400px;" value="#{controllerProcessDepartment.strDescription}"></h:inputTextarea>
	    </label>
	</td>
    </tr>
    <tr><td style="border-bottom:1px solid #bbb;"></td></tr>
    <tr><input name="frmChk" type="hidden" value="0" />
	<td style="color:#bbb;">
	    <h:commandButton action="#{controllerProcessDepartment.manipulateDepartment()}" value="save" style="margin-left:0;padding-left:0;" /> | <input type="reset" id="reset" value="clear" />
	</td>
    </tr>
</tbody>
</table>
</h:form>  
</ui:define>

<ui:define name="cph_PostLoadScripts">
<h:outputScript>//<![CDATA[
var x=document.forms[0];
try{fncFrmLoad(x);
    var validate=function(x){
	var t=fncValidateFrm(x);
	    if(t){
		
	    }
	    return t;
	};
    x.onsubmit=function(){
	var t=validate(this);
	if(!t) return false;
	//if(t) x.submit();
	//return false;
    };
}catch(e){alert(e);}
$(document).ready(function(){
   
});
//]]></h:outputScript>
</ui:define>
</ui:composition>

src/main/webapp/Administrators/Departments/Welcome.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		    xmlns:h="http://java.sun.com/jsf/html"
		    template="./../../WEB-INF/abstracts/tplAdmin2.xhtml">
<ui:define name="cph_Title">Welcome</ui:define>


<ui:define name="cph_PageStyles">
<style type="text/css" media="all">
ul.event_tab.menu{width:16%;}
</style>
</ui:define>


<ui:define name="cph_Heading">Dashboard</ui:define>


<ui:define name="cph_Content">
<ul id="updateList1" class="event_tab menu nav">
<li class="heading">Departments</li>
<ui:repeat value="#{controllerFetchDepartmentData.lstDepartments}" var="department">
<li>
    <span class="attribute">
	<a href="Manage_Department.xhtml?department_id=#{department.ID}" class="title">#{department.name}</a>
	<a title="Edit" href="Manage_Department.xhtml?department_id=#{department.ID}" class="action right text-right"><img style="cursor:pointer;border:0 none;" src="/res/img.icon.edit.png" title="Edit" alt="edit" /></a>
    </span>
    <span class="attribute"><span class="bold">Description : </span> 
	<h:outputLabel value="#{department.description}"></h:outputLabel>
    </span>
    <span class="attribute"><span class="bold">Events : </span> <h:outputText value="#{department.departmentEvents.size()}"/></span>
</li>
</ui:repeat>
<li></li>
<li class="right"><a href="Manage_Department.xhtml">Add New</a></li>
</ul>

<ul id="updateList2" class="event_tab menu nav">
<li class="heading">New Events</li>
<ui:repeat value="#{controllerFetchDepartmentData.lstPendingEvents}" var="event">
<li>
    <span class="attribute">
	<a href="Manage_Event.xhtml?event_id=#{event.ID}" class="title">#{event.title}</a>
	<a title="Edit" href="Manage_Event.xhtml?event_id=#{event.ID}" class="action right text-right"><img style="cursor:pointer;border:0 none;" src="/res/img.icon.edit.png" title="Edit" alt="edit" /></a>
	<h:outputText value="#{event.description}"/>
    </span>
    <span class="attribute"><span class="bold">Begin : </span> <h:outputText value="#{event.EBegin}"/></span>
    <span class="attribute"><span class="bold">End : </span> <h:outputText value="#{event.EEnd}"/></span>
    <span class="attribute"><span class="bold">Held by : </span> <h:outputText value="#{event.department.name}"/></span>
    <span class="attribute"><span class="bold">Held at : </span> <h:outputText value="#{event.venue.title}"/></span>
    <span class="attribute">
    <span class="bold">Students attending the Event : </span><br />
    <ui:repeat value="#{event.studentList}" var="student">
	<span>#{student.FName} #{student.FName} (#{student.auth.username})</span><br />
    </ui:repeat>
    <span class="bold">Total</span><h:outputText value=" #{event.studentList.size()}"></h:outputText>
    </span>
    <span class="attribute"><span class="bold">No. of Comments : </span> <h:outputText value="#{event.comments.size()}"/></span>
    <span class="attribute"><a title="Delete" accesskey="#{event.ID}" class="action delete"><img style="cursor:pointer;border:0 none;" src="/res/img.icon.delete.png" title="Delete" alt="Delete" /></a></span>
</li>
</ui:repeat>
<li class="right"><a href="Manage_Event.xhtml">Add New</a></li>
</ul>
    
<ul id="updateList3" class="event_tab menu nav">
<li class="heading">Approved Events</li>
<ui:repeat value="#{controllerFetchDepartmentData.lstActiveEvents}" var="event">
<li>
    <span class="attribute">
	<a href="Manage_Event.xhtml?event_id=#{event.ID}" class="title">#{event.title}</a>
	<a title="Edit" href="Manage_Event.xhtml?event_id=#{event.ID}" class="action right text-right"><img style="cursor:pointer;border:0 none;" src="/res/img.icon.edit.png" title="Edit" alt="edit" /></a>
	<h:outputText value="#{event.description}"/>
    </span>
    <span class="attribute"><span class="bold">Begin : </span> <h:outputText value="#{event.EBegin}"/></span>
    <span class="attribute"><span class="bold">End : </span> <h:outputText value="#{event.EEnd}"/></span>
    <span class="attribute"><span class="bold">Held by : </span> <h:outputText value="#{event.department.name}"/></span>
    <span class="attribute"><span class="bold">Held at : </span> <h:outputText value="#{event.venue.title}"/></span>
    <span class="attribute">
    <span class="bold">Students attending the Event : </span><br />
    <ui:repeat value="#{event.studentList}" var="student">
	<span>#{student.FName} #{student.FName} (#{student.auth.username})</span><br />
    </ui:repeat>
    <span class="bold">Total</span><h:outputText value=" #{event.studentList.size()}"></h:outputText>
    </span>
    <span class="attribute"><span class="bold">No. of Comments : </span> <h:outputText value="#{event.comments.size()}"/></span>
    <span class="attribute"><a title="Delete" accesskey="#{event.ID}" class="action delete"><img style="cursor:pointer;border:0 none;" src="/res/img.icon.delete.png" title="Delete" alt="Delete" /></a></span>
</li>
</ui:repeat>
<li class="right"><a href="Manage_Event.xhtml">Add New</a></li>
</ul>
    
<ul id="updateList4" class="event_tab menu nav">
<li class="heading">Declined Events</li>
<ui:repeat value="#{controllerFetchDepartmentData.lstDeclinedEvents}" var="event">
<li>
    <span class="attribute">
	<a href="#" class="title">#{event.title}</a>
	<h:outputText value="#{event.description}"/>
    </span>
    <span class="attribute"><span class="bold">Begin : </span> <h:outputText value="#{event.EBegin}"/></span>
    <span class="attribute"><span class="bold">End : </span> <h:outputText value="#{event.EEnd}"/></span>
    <span class="attribute"><span class="bold">Held by : </span> <h:outputText value="#{event.department.name}"/></span>
    <span class="attribute"><span class="bold">Held at : </span> <h:outputText value="#{event.venue.title}"/></span>
    <span class="attribute">
    <span class="bold">Students attending the Event : </span><br />
    <ui:repeat value="#{event.studentList}" var="student">
	<span>#{student.FName} #{student.FName} (#{student.auth.username})</span><br />
    </ui:repeat>
    <span class="bold">Total</span><h:outputText value=" #{event.studentList.size()}"></h:outputText>
    </span>
    <span class="attribute"><span class="bold">No. of Comments : </span> <h:outputText value="#{event.comments.size()}"/></span>
</li>
</ui:repeat>
</ul>
    
<ul id="updateList5" class="event_tab menu nav">
<li class="heading">Cancelled Events</li>
<ui:repeat value="#{controllerFetchDepartmentData.lstCancelledEvents}" var="event">
<li>
    <span class="attribute">
	<a href="#" class="title">#{event.title}</a>
	<h:outputText value="#{event.description}"/>
    </span>
    <span class="attribute"><span class="bold">Begin : </span> <h:outputText value="#{event.EBegin}"/></span>
    <span class="attribute"><span class="bold">End : </span> <h:outputText value="#{event.EEnd}"/></span>
    <span class="attribute"><span class="bold">Held by : </span> <h:outputText value="#{event.department.name}"/></span>
    <span class="attribute"><span class="bold">Held at : </span> <h:outputText value="#{event.venue.title}"/></span>
    <span class="attribute">
    <span class="bold">Students attending the Event : </span><br />
    <ui:repeat value="#{event.studentList}" var="student">
	<span>#{student.FName} #{student.FName} (#{student.auth.username})</span><br />
    </ui:repeat>
    <span class="bold">Total</span><h:outputText value=" #{event.studentList.size()}"></h:outputText>
    </span>
    <span class="attribute"><span class="bold">No. of Comments : </span> <h:outputText value="#{event.comments.size()}"/></span>
</li>
</ui:repeat>
</ul>
</ui:define>

<ui:define name="cph_PostLoadScripts">
<h:outputScript>//<![CDATA[
$(document).ready(function(){
var refreshPanels=function(){
	$('ul.event_tab.menu').each(function(){
	     $(this).show(0);
	     if($(this).children('li').length==1) $(this).hide(0);
	});
    }
    $(document).on('click', 'a.delete.action', function(){
			    if(confirm_delete()){
			    $.get('ajax/cancel_event?id='+ $(this).attr('accesskey'), function(){
								$('ul#updateList2').load('Welcome.xhtml #updateList2 li',
									function(){
									    $('ul#updateList3').load('Welcome.xhtml #updateList3 li',
										   function(){
											$('ul#updateList4').load('Welcome.xhtml #updateList4 li',
											    function(){
												$('ul#updateList5').load('Welcome.xhtml #updateList5 li',
												    function(){
													refreshPanels();
													});
											    });
										   });
										});
							});
							}
				});
	    refreshPanels();
	});
//]]></h:outputScript>
</ui:define>
</ui:composition>

src/main/webapp/Administrators/Departments/index.xhtml
<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta http-equiv="REFRESH" content="0; Welcome.xhtml" />
</head>
</html>