src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/entities/Event.java
package edu.iit.sat.itmd4515.abhimani.fp.domain.entities;

import edu.iit.sat.itmd4515.abhimani.fp.domain.AbstractEntityUnit;
import edu.iit.sat.itmd4515.abhimani.fp.domain.EventState;
import edu.iit.sat.itmd4515.abhimani.fp.domain.relations.Comment;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Future;
import javax.validation.constraints.Size;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
@Entity
@Table(name = "event_store")
@NamedQueries({
    @NamedQuery(name = "Events.retrieveAll", query = "SELECT e FROM Event AS e"),
    @NamedQuery(name = "Events.findByID", query = "SELECT e FROM Event AS e WHERE e.PID=:PID"),
    @NamedQuery(name = "Events.retrieveByDepartment", query = "SELECT e FROM Event AS e WHERE e.Dept=:Dept"),
    @NamedQuery(name = "Events.retrieveByVenue", query = "SELECT e FROM Event AS e WHERE e.Ven=:Ven")
})
public class Event
	extends AbstractEntityUnit
	implements Comparable<Event>, Serializable{
    //COLUMNS
    @Column(name = "Title", nullable = false, length = 255, unique = true)
    @Size(min = 4)
    private String Title;

    @Column(name = "Description", length = 2000)
    private String Description;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EBegin", nullable = false)
    @Future
    private Date EBegin;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EEnd", nullable = false)
    @Future
    private Date EEnd;

    @Column(name = "AState", nullable = false)
    private EventState AState=EventState.NEW;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CDate", nullable = false, insertable = true, updatable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private final Date CDate=new Date();

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MDate", insertable = false, updatable = true, columnDefinition = "TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
    private Date MDate;

    @JoinColumn(name = "Event_Dept_ID", referencedColumnName = "PID", nullable = false)
    @ManyToOne(optional = false)
    private Department Dept;

    @JoinColumn(name = "Event_Venue_ID", referencedColumnName = "PID", nullable = false)
    @ManyToOne(optional = false)
    private Venue Ven;

    @OneToMany(cascade = CascadeType.REMOVE, mappedBy = "Evt")
    private List<Comment> lstComments;

    @ManyToMany(mappedBy = "lstEvents")
    private List<Student> lstStudents=new ArrayList<>();

    //CONSTRUCTS
    public Event(){
	super();
    }

    public Event(Department Dept, Venue Ven, String Title, String Description, Date EBegin, Date EEnd, EventState AState){
	this.Dept=Dept;
	this.Ven=Ven;
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
	this.AState=AState;
    }

    public Event(Department Dept, Venue Ven, String Title, String Description, Date EBegin, Date EEnd){
	this.Dept=Dept;
	this.Ven=Ven;
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
    }

    public Event(String Title, String Description, Date EBegin, Date EEnd, EventState AState){
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
	this.AState=AState;
    }

    public Event(String Title, String Description, Date EBegin, Date EEnd){
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
    }

    //PROPERTIES
    public String getTitle(){
	return Title;
    }

    public void setTitle(String Title){
	this.Title=Title.trim();
    }

    public String getDescription(){
	return Description;
    }

    public void setDescription(String Description){
	this.Description=Description.trim();
    }

    public Date getRawEBegin(){
	return EBegin;
    }

    public String getEBegin(){
	return EBegin.toString();
    }

    public void setEBegin(Date EBegin){
	this.EBegin=EBegin;
    }

    public Date getRawEEnd(){
	return EEnd;
    }

    public String getEEnd(){
	return EEnd.toString();
    }

    public void setEEnd(Date EEnd){
	this.EEnd=EEnd;
    }

    public EventState getRawAState(){
	return AState;
    }

    public String getAState(){
	return AState.toString();
    }

    public void setAState(EventState AState){
	this.AState=AState;
    }

    /**
     * This field is inserted only once automatically upon row creation.
     *
     * @return Returns Creation Date
     */
    public String getCDate(){
	return CDate.toString();
    }

    /**
     * This field is updated automatically receives last update date.
     *
     * @return Returns Last Modified Date
     */
    public String getMDate(){
	return ((MDate==null) ? "-" : MDate.toString());
    }

    //RELATIONS
    public Department getDepartment(){
	return Dept;
    }

    public void setDepartment(Department Dept){
	this.Dept=Dept;
    }

    public Venue getVenue(){
	return Ven;
    }

    public void setVenue(Venue Ven){
	this.Ven=Ven;
    }

    public List<Student> getStudentList(){
	return lstStudents;
    }

    public void addStudent(Student stud){
	if(!this.getStudentList().contains(stud))
	    this.lstStudents.add(stud);
	if(!stud.getEventList().contains(this))
	    stud.attendEvent(this);
    }

    public void removeStudent(Student stud){
	if(this.getStudentList().contains(stud))
	    this.lstStudents.remove(stud);
	if(stud.getEventList().contains(this))
	    stud.unAttendEvent(this);
    }

    /**
     * Holds a list of comments received for the event.
     *
     * @return Returns a list of Comments from Students for the Event
     */
    public List<Comment> getComments(){
	return lstComments;
    }

    //IMPLEMENTATION
    /**
     * CompareTo implemented on the Title field.
     *
     * @param el Expects an element of type Event
     */
    @Override
    public int compareTo(Event el){
	return (this.getEBegin().compareTo(el.getEBegin()));
    }

    //OVERRIDES
    @Override
    public boolean equals(Object el){
	if(!(el instanceof Event))
	    return false;
	try{
	    Event tstEvt=(Event)el;
	    if(!(Integer.compare(this.hashCode(), tstEvt.hashCode())==0))
		return false;
	}catch(Exception ex){
	    return false;
	}
	return true;
    }

    @Override
    public String toString(){
	try{
	    return ("/Entities.Event{ID:"+this.getPID()+", Dept_ID:\""+this.getDepartment().getPID()+"\", Department:\""+this.getDepartment().getName()+"\", Venue_ID:\""+this.getVenue().getPID()+"\", Venue:\""+this.getVenue().getTitle()+"\", Title:\""+this.getTitle()+"\", Description:{Length:"+((this.getDescription()==null) ? 0 : this.getDescription().length())+"}, EBegin:\""+this.getEBegin()+"\", EEnd:\""+this.getEEnd()+"\", Comments:"+this.getComments().size()+", State:"+this.getAState().toUpperCase()+", Create_Date:\""+this.getCDate()+"\", Last_Modified:\""+this.getMDate()+"\"}");
	}catch(Exception ex){
	    return ex.toString();
	}
    }
}

src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/entities/Student.java
package edu.iit.sat.itmd4515.abhimani.fp.domain.entities;

import edu.iit.sat.itmd4515.abhimani.fp.domain.AbstractEntityUnit;
import edu.iit.sat.itmd4515.abhimani.fp.domain.relations.Comment;
import edu.iit.sat.itmd4515.abhimani.fp.domain.authorization.StudentLogin;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.OneToOne;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
@Entity
@Table(name="students")
@NamedQueries({
    @NamedQuery(name="Students.retrieveAll", query="SELECT s FROM Student AS s"),
    @NamedQuery(name="Students.findByID", query="SELECT s FROM Student AS s WHERE s.PID=:PID"),
    @NamedQuery(name="Students.findByNumber", query="SELECT s FROM Student AS s WHERE s.Student_Number=:Number"),
    @NamedQuery(name="Students.findByEmailID", query="SELECT s FROM Student AS s WHERE s.EmailID=:EmailID")
})
public class Student
	extends AbstractEntityUnit
	implements Comparable<Student>, Serializable{
    //COLUMNS
    @Column(name="Student_Number", nullable=false, length=36, unique=true, updatable=false)
    private final String Student_Number;

    @Column(name="FName", nullable=false, length=255)
    @Size(min=2)
    private String FName;

    @Column(name="LName", nullable=false, length=255)
    @Size(min=2)
    private String LName;

    @Pattern(regexp="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\."+"[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@"+"(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", message="Invalid Email ID.")
    @Column(name="EmailID", nullable=false, length=255, unique=true)
    private String EmailID;

    @Column(name="Gender", nullable=false)
    private char Gender='M'; //M, F

    @Column(name="Phone", nullable=false, length=10)
    @Min(1000000000)
    private long Phone=0;

    @Column(name="NotifyEvents", nullable=false)
    private boolean NotifyEvents;

    @Column(name="Special", length=2000)
    private String Special;

    @OneToOne(cascade=CascadeType.PERSIST, optional=false, fetch=FetchType.LAZY, orphanRemoval=false)
    @JoinColumn(name="LoginID", unique=true, nullable=false, updatable=false)
    private StudentLogin auth;

    @OneToMany(cascade=CascadeType.REMOVE, mappedBy="Stud")
    private List<Comment> lstComments;

    @ManyToMany(cascade=CascadeType.REMOVE, fetch=FetchType.EAGER)
    @JoinTable(
	    name="event_student_attends",
	    joinColumns={
		@JoinColumn(name="Student_ID", referencedColumnName="PID")},
	    inverseJoinColumns={
		@JoinColumn(name="Event_ID", referencedColumnName="PID")})
    private List<Event> lstEvents=new ArrayList<>();

    //CONSTRUCTS
    public Student(){
	super();
	this.Student_Number=UUID.randomUUID().toString();
    }

    public Student(String FName, String LName, char Gender, long Phone, String EmailID, boolean NotifyEvents, String Special){
	this.Student_Number=UUID.randomUUID().toString();
	this.FName=FName.trim();
	this.LName=LName.trim();
	this.Gender=Gender;
	this.Phone=Phone;
	this.EmailID=EmailID.trim();
	this.NotifyEvents=NotifyEvents;
	this.Special=Special.trim();
    }

    public Student(String FName, String LName, char Gender, long Phone, String EmailID, boolean NotifyEvents){
	this.Student_Number=UUID.randomUUID().toString();
	this.FName=FName.trim();
	this.LName=LName.trim();
	this.Gender=Gender;
	this.Phone=Phone;
	this.EmailID=EmailID.trim();
	this.NotifyEvents=NotifyEvents;
    }

    //PROPERTIES
    /**
     * Has 1-1 mapping with the StudentLogin and hold the login credentials.
     *
     * @return Returns the StudentLogin for authentication of a Student
     */
    public StudentLogin getAuth(){
	return this.auth;
    }

    /**
     * Can be used to update the Student credentials.
     *
     * @param auth Expects an element of type StudentLogin for the authenticated
     * Student
     */
    public void setAuth(StudentLogin auth){
	this.auth=auth;
    }

    /**
     * Every Student is assigned a permanent 36-char Unique ID upon creation,
     * the field not being updatable.
     *
     * @return Returns A Unique Number assigned to the Student
     */
    public String getStudent_Number(){
	return Student_Number;
    }

    public String getFName(){
	return FName;
    }

    public void setFName(String FName){
	this.FName=FName.trim();
    }

    public String getLName(){
	return LName;
    }

    public void setLName(String LName){
	this.LName=LName.trim();
    }

    public char getGender(){
	return Gender;
    }

    public void setGender(char Gender){
	this.Gender=Gender;
    }

    public long getPhone(){
	return Phone;
    }

    public void setPhone(long Phone){
	this.Phone=Phone;
    }

    public String getEmailID(){
	return EmailID;
    }

    public void setEmailId(String EmailID){
	this.EmailID=EmailID.trim();
    }

    /**
     * A flag to hold whether a student can be notified of any event.
     *
     * @return Returns True or False if the Student can be notified for Events
     */
    public boolean isNotifyEvents(){
	return NotifyEvents;
    }

    public void setNotifyEvents(boolean NotifyEvents){
	this.NotifyEvents=NotifyEvents;
    }

    public String getSpecial(){
	return Special;
    }

    /**
     * To hold any special note of the student.
     *
     * @param Special Expects an Special Administrative Note of the Student if any
     */
    public void setSpecial(String Special){
	this.Special=Special.trim();
    }

    //RELATIONS
    /**
     * Holds a list of events the Student has attended or will attend.
     *
     * @return Returns a list of Events the Student is attending
     */
    public List<Event> getEventList(){
	return lstEvents;
    }

    public void attendEvent(Event event){
	if(!this.getEventList().contains(event))
	    this.lstEvents.add(event);
	if(!event.getStudentList().contains(this))
	    event.addStudent(this);
    }

    public void unAttendEvent(Event event){
	if(this.getEventList().contains(event))
	    this.lstEvents.remove(event);
	if(event.getStudentList().contains(this))
	    event.removeStudent(this);
    }

    public List<Comment> getComments(){
	return lstComments;
    }

    //IMPLEMENTATION
    /**
     * CompareTo implemented on the Email ID field which is always unique and
     * therefore a business rule.
     *
     * @param el Expects an element of type Student
     */
    @Override
    public int compareTo(Student el){
	return (this.getEmailID().compareTo(el.getEmailID()));
    }

    //OVERRIDES
    @Override
    public boolean equals(Object el){
	if(!(el instanceof Student))
	    return false;
	try{
	    Student tstStudent=(Student)el;
	    if(!(Integer.compare(this.hashCode(), tstStudent.hashCode())==0))
		return false;
	}catch(Exception ex){
	    ex.printStackTrace();
	    return false;
	}
	return true;
    }

    @Override
    public String toString(){
	try{
	    return ("/Entities.Student{ID:"+this.getPID()+", Number:"+this.getStudent_Number()+", Name:{First:\""+this.getFName()+"\", Last:\""+this.getLName()+"\"}, Contact:{Phone:"+this.getPhone()+", EmailID:"+this.getEmailID()+"}, NotifyEvents:"+Boolean.toString(this.isNotifyEvents())+", Special:{Length:"+((this.getSpecial()==null) ? 0 : this.getSpecial().length())+"}, Comments:"+this.getComments().size()+"}");
	}catch(Exception ex){
	    return ex.toString();
	}
    }
}

src/main/webapp/Administrators/Users/Add_Administrator.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		   xmlns:h="http://java.sun.com/jsf/html"
		   xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
		   xmlns:f="http://java.sun.com/jsf/core"
		    template="./../../WEB-INF/abstracts/tplSuperAdmin3.xhtml">
<ui:define name="cph_Title">New Administrator</ui:define>

<ui:define name="cph_Heading">Create Administrator</ui:define>

<ui:define name="cph_Content">
<h:form id="x0">
<table id="tblx">
<tbody>
    <tr><td style="border-top:1px solid #bbb;"></td></tr>
     <tr><th style="border-bottom:1px solid #bbb;">Credentials</th></tr>
     <tr>
	<td><label>
	    <span class="bold">Username</span> <span class="red">*</span><br />
	     <h:inputText id="txtUsername" title="Enter Username" p:placeholder="Enter Username" maxlength="155" alt="1" value="#{controllerProcessUsers.strUsername}" />
	    </label>
	</td>
    </tr>
     <tr>
	<td><label>
	    <span class="bold">Role</span> <span class="red">*</span><br />
	     <h:selectOneListbox title="Select Gender" p:placeholder="Select Role" id="ddlRole" value="#{controllerProcessUsers.intRole}">
		 <f:selectItem itemValue="0" itemLabel="SUPER_ADMIN" />
		<f:selectItem itemValue="1" itemLabel="DEPT_ADMIN" />
		<f:selectItem itemValue="2" itemLabel="VENUE_ADMIN" />
	    </h:selectOneListbox>
	    </label>
	</td>
    </tr>
     <tr>
	<td><label>
	    <span class="bold">Password</span> <span class="red">*</span><br />
	    <h:inputSecret id="txtNewPassword" title="Enter New Password" p:placeholder="Enter New Password" maxlength="155" alt="1" size="6" value="#{controllerProcessUsers.strNewPassword}" /><br /><br />
	    <h:inputSecret id="txtNewPasswordConfirm" title="Confirm New Password" p:placeholder="Confirm New Password" maxlength="155" alt="1" size="6" />
	    </label>
	</td>
    </tr>
    <tr><td style="border-bottom:1px solid #bbb;"></td></tr>
    <tr><input name="frmChk" type="hidden" value="0" />
	<td style="color:#bbb;">
	    <h:commandButton action="#{controllerProcessUsers.createAdministrator()}" value="create" style="margin-left:0;padding-left:0;" /> | <input type="reset" id="reset" value="clear" />
	</td>
    </tr>
</tbody>
</table>
</h:form>  
</ui:define>

<ui:define name="cph_PostLoadScripts">
<h:outputScript>//<![CDATA[
var x=document.forms[0];
try{fncFrmLoad(x);
    var validate=function(x){
	var t=fncValidateFrm(x);
	    if(t){
		if($(document.getElementById('x0:txtNewPassword')).val()!=$(document.getElementById('x0:txtNewPasswordConfirm')).val()){
		    $(document.getElementById('x0:txtNewPasswordConfirm')).focus();
		    $(document.getElementById('x0:txtNewPasswordConfirm')).addClass('redline');
		    $('div#msgBox').text('New Passwords must match.');
		    t=false;
		}else $(document.getElementById('x0:txtNewPasswordConfirm')).removeClass('redline');
	    }
	    return t;
	};
    x.onsubmit=function(){
	var t=validate(this);
	if(!t) return false;
	//if(t) x.submit();
	//return false;
    };
}catch(e){alert(e);}
$(document).ready(function(){
   
});
//]]></h:outputScript>
</ui:define>
</ui:composition>

src/main/webapp/Administrators/Users/Welcome.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		    xmlns:h="http://java.sun.com/jsf/html"
		    template="./../../WEB-INF/abstracts/tplSuperAdmin3.xhtml">
<ui:define name="cph_Title">Welcome</ui:define>


<ui:define name="cph_PageStyles">
<style type="text/css" media="all">
ul.event_tab.menu{width:45%;}
</style>
</ui:define>


<ui:define name="cph_Heading">Dashboard</ui:define>


<ui:define name="cph_Content">
<ul id="updateList1" class="event_tab menu nav">
<li class="heading">Administrators</li>
<ui:repeat value="#{controllerFetchUsers.lstAdministrators}" var="authentication">
<li>
    <span class="attribute">
	<a href="#" class="title">#{authentication.username}</a>
	<a href="#" onclick="javascript:return confirm_delete();" accesskey="#{authentication.ID}" class="action admin_delete right text-right"><img style="cursor:pointer;border:0 none;" src="/res/img.icon.delete.png" title="delete" alt="delete" /></a>	
    </span>
    <span class="attribute"><span class="bold">Role : </span> 
	<ui:repeat value="#{authentication.roles}" var="role">
	    <h:outputText value="#{role.name}"/>
	</ui:repeat>
    </span>
</li>
</ui:repeat>
<li></li>
<li class="right"><a href="Add_Administrator.xhtml">Add New</a></li>
</ul>

<ul id="updateList2" class="event_tab menu nav">
<li class="heading">Students</li>
<ui:repeat value="#{controllerFetchUsers.lstStudents}" var="student">
<li>
    <span class="attribute">
	<a title="Edit Note" href="Student_Note.xhtml?student_id=#{student.PID}" class="title">#{student.FName} #{student.LName} (#{student.auth.username})</a>
	<a title="Edit Note" href="Student_Note.xhtml?student_id=#{student.PID}" class="action right text-right"><img style="cursor:pointer;border:0 none;" src="/res/img.icon.edit.png" title="Edit Note" alt="edit" /></a>
    </span>
    <span class="attribute"><span class="bold">Unique Student Number : </span> <h:outputText value="#{student.student_Number}"/></span>
    <span class="attribute"><span class="bold">Gender : </span> <h:outputText value="#{student.gender}"/></span>
    <span class="attribute"><span class="bold">Email ID : </span> <h:outputLink value="#{student.emailID}">#{student.emailID}</h:outputLink></span>
    <span class="attribute"><span class="bold">Phone : </span> <h:outputText value="#{student.phone==0 ? '-': student.phone}"/></span>
    <span class="attribute">
	<span class="bold">Events : </span><h:outputText value="0" rendered="#{student.eventList.size() eq 0}" /><br />
    <ui:repeat value="#{student.eventList}" var="event">
	<span>- #{event.title} (#{event.venue.title})</span><br />
    </ui:repeat>
    <span class="bold">Total </span><h:outputText value=" #{student.eventList.size()}"></h:outputText>
    </span>
    <span class="attribute"><span class="bold">Notify for Events : </span> <h:outputText value="#{student.notifyEvents}"/></span>
    <span class="attribute"><span class="bold">Comments : </span> <h:outputText value="#{student.comments.size()}"/></span>
    <span class="attribute"><span class="bold">Remarks : </span> <h:outputText value="#{student.special}"/></span>    
</li>
</ui:repeat>
<li></li>
<li class="right"><a href="Student_Profile.xhtml">Add New</a></li>
</ul>
</ui:define>

<ui:define name="cph_PostLoadScripts">
<h:outputScript>//<![CDATA[
$(document).ready(function(){
var refreshPanels=function(){
	$('ul.event_tab.menu').each(function(){
	     $(this).show(0);
	     if($(this).children('li').length==1) $(this).hide(0);
	});
    }
    $('a.admin_delete').click(function(){
			    $.get('ajax/delete_admin?id='+ $(this).attr('accesskey'), function(){
												$('ul#updateList1').load('Welcome.xhtml #updateList1 li',
												    function(){
													refreshPanels();
													});
											});
				});
		    });
//]]></h:outputScript>
</ui:define>
</ui:composition>

src/main/webapp/Administrators/Users/index.xhtml
<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta http-equiv="REFRESH" content="0; Welcome.xhtml" />
</head>
</html>