src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/authorization/StudentLogin.java
package edu.iit.sat.itmd4515.abhimani.fp.domain.authorization;

import edu.iit.sat.itmd4515.abhimani.fp.EncryptText;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
@Entity
@Table(name="auth_students_login")
@NamedQueries({
    @NamedQuery(name="StudentLogin.authenticate", query="SELECT l FROM StudentLogin AS l WHERE l.Username=:uname AND l.Password IS NOT NULL")
})
public class StudentLogin
	implements Comparable<StudentLogin>, Serializable{
    //COLUMNS
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(nullable=false)
    protected long LoginID;

    @Column(length=255, unique=true, updatable=false)
    @Size(min=4)
    private String Username;

    @Column(name="enc_pwd", length=64)
    @Size(min=8, max=40)
    private String Password;

    //CONSTRUCT
    private StudentLogin(){
	super();
    }

    /**
     * You must not initialize and use an instance of this class with the
     * default constructor, instead use the Student.getAuth() and
     * Student.setAuth(StudentLogin auth) methods to access or update the
     * credentials; Use this constructor only to use the matchLogin(String
     * Password) and authenticate the user.
     *
     * @param Username Expects a Username to initialize the class
     */
    public StudentLogin(String Username){
	this.Username=Username.trim();
    }

    //PROPERTIES
    public long getLoginID(){
	return this.LoginID;
    }

    public String getUsername(){
	return this.Username;
    }

    public String getPasswordKey(){
	return this.Password;
    }

    /**
     * Password is sha256ed and saved.
     *
     */
    @PrePersist
    @PreUpdate
    private void cryptPassword(){
	this.Password=EncryptText.crypt(this.Password);
    }

    public void setPassword(String Password){
	this.Password=Password.trim();
    }

    /**
     * Can be used to authenticate the user.
     *
     *
     * @param Password Expects Student password for matching
     *
     * @return A Boolean True or False
     */
    public boolean matchLogin(String Password){
	return EncryptText.hashEquals(this.getPasswordKey(), Password);
    }

    //IMPLEMENTATION
    /**
     * CompareTo implemented on the Username of the Student which is unqiue.
     *
     * @param el Expects an element of type StudentLogin
     */
    @Override
    public int compareTo(StudentLogin el){
	return (this.getUsername().compareTo(el.getUsername()));
    }

    //OVERRIDES
    @Override
    public int hashCode(){
	return ((this.getLoginID()>0) ? Long.hashCode(this.getLoginID()) : 0);
    }

    @Override
    public boolean equals(Object el){
	if(!(el instanceof StudentLogin))
	    return false;
	try{
	    StudentLogin tstLogin=(StudentLogin)el;
	    if(!(Integer.compare(this.hashCode(), tstLogin.hashCode())==0))
		return false;
	}catch(Exception ex){
	    return false;
	}
	return true;
    }

    @Override
    public String toString(){
	try{
	    return ("NOT_AUTHORIZED");
	}catch(Exception ex){
	    return ex.toString();
	}
    }
}

src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/entities/Event.java
package edu.iit.sat.itmd4515.abhimani.fp.domain.entities;

import edu.iit.sat.itmd4515.abhimani.fp.domain.AbstractEntityUnit;
import edu.iit.sat.itmd4515.abhimani.fp.domain.EventState;
import edu.iit.sat.itmd4515.abhimani.fp.domain.relations.Comment;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Future;
import javax.validation.constraints.Size;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
@Entity
@Table(name = "event_store")
@NamedQueries({
    @NamedQuery(name = "Events.retrieveAll", query = "SELECT e FROM Event AS e"),
    @NamedQuery(name = "Events.findByID", query = "SELECT e FROM Event AS e WHERE e.PID=:PID"),
    @NamedQuery(name = "Events.retrieveByDepartment", query = "SELECT e FROM Event AS e WHERE e.Dept=:Dept"),
    @NamedQuery(name = "Events.retrieveByVenue", query = "SELECT e FROM Event AS e WHERE e.Ven=:Ven")
})
public class Event
	extends AbstractEntityUnit
	implements Comparable<Event>, Serializable{
    //COLUMNS
    @Column(name = "Title", nullable = false, length = 255, unique = true)
    @Size(min = 4)
    private String Title;

    @Column(name = "Description", length = 2000)
    private String Description;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EBegin", nullable = false)
    @Future
    private Date EBegin;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EEnd", nullable = false)
    @Future
    private Date EEnd;

    @Column(name = "AState", nullable = false)
    private EventState AState=EventState.NEW;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CDate", nullable = false, insertable = true, updatable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private final Date CDate=new Date();

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MDate", insertable = false, updatable = true, columnDefinition = "TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
    private Date MDate;

    @JoinColumn(name = "Event_Dept_ID", referencedColumnName = "PID", nullable = false)
    @ManyToOne(optional = false)
    private Department Dept;

    @JoinColumn(name = "Event_Venue_ID", referencedColumnName = "PID", nullable = false)
    @ManyToOne(optional = false)
    private Venue Ven;

    @OneToMany(cascade = CascadeType.REMOVE, mappedBy = "Evt")
    private List<Comment> lstComments;

    @ManyToMany(mappedBy = "lstEvents")
    private List<Student> lstStudents=new ArrayList<>();

    //CONSTRUCTS
    public Event(){
	super();
    }

    public Event(Department Dept, Venue Ven, String Title, String Description, Date EBegin, Date EEnd, EventState AState){
	this.Dept=Dept;
	this.Ven=Ven;
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
	this.AState=AState;
    }

    public Event(Department Dept, Venue Ven, String Title, String Description, Date EBegin, Date EEnd){
	this.Dept=Dept;
	this.Ven=Ven;
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
    }

    public Event(String Title, String Description, Date EBegin, Date EEnd, EventState AState){
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
	this.AState=AState;
    }

    public Event(String Title, String Description, Date EBegin, Date EEnd){
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
    }

    //PROPERTIES
    public String getTitle(){
	return Title;
    }

    public void setTitle(String Title){
	this.Title=Title.trim();
    }

    public String getDescription(){
	return Description;
    }

    public void setDescription(String Description){
	this.Description=Description.trim();
    }

    public Date getRawEBegin(){
	return EBegin;
    }

    public String getEBegin(){
	return EBegin.toString();
    }

    public void setEBegin(Date EBegin){
	this.EBegin=EBegin;
    }

    public Date getRawEEnd(){
	return EEnd;
    }

    public String getEEnd(){
	return EEnd.toString();
    }

    public void setEEnd(Date EEnd){
	this.EEnd=EEnd;
    }

    public EventState getRawAState(){
	return AState;
    }

    public String getAState(){
	return AState.toString();
    }

    public void setAState(EventState AState){
	this.AState=AState;
    }

    /**
     * This field is inserted only once automatically upon row creation.
     *
     * @return Returns Creation Date
     */
    public String getCDate(){
	return CDate.toString();
    }

    /**
     * This field is updated automatically receives last update date.
     *
     * @return Returns Last Modified Date
     */
    public String getMDate(){
	return ((MDate==null) ? "-" : MDate.toString());
    }

    //RELATIONS
    public Department getDepartment(){
	return Dept;
    }

    public void setDepartment(Department Dept){
	this.Dept=Dept;
    }

    public Venue getVenue(){
	return Ven;
    }

    public void setVenue(Venue Ven){
	this.Ven=Ven;
    }

    public List<Student> getStudentList(){
	return lstStudents;
    }

    public void addStudent(Student stud){
	if(!this.getStudentList().contains(stud))
	    this.lstStudents.add(stud);
	if(!stud.getEventList().contains(this))
	    stud.attendEvent(this);
    }

    public void removeStudent(Student stud){
	if(this.getStudentList().contains(stud))
	    this.lstStudents.remove(stud);
	if(stud.getEventList().contains(this))
	    stud.unAttendEvent(this);
    }

    /**
     * Holds a list of comments received for the event.
     *
     * @return Returns a list of Comments from Students for the Event
     */
    public List<Comment> getComments(){
	return lstComments;
    }

    //IMPLEMENTATION
    /**
     * CompareTo implemented on the Title field.
     *
     * @param el Expects an element of type Event
     */
    @Override
    public int compareTo(Event el){
	return (this.getEBegin().compareTo(el.getEBegin()));
    }

    //OVERRIDES
    @Override
    public boolean equals(Object el){
	if(!(el instanceof Event))
	    return false;
	try{
	    Event tstEvt=(Event)el;
	    if(!(Integer.compare(this.hashCode(), tstEvt.hashCode())==0))
		return false;
	}catch(Exception ex){
	    return false;
	}
	return true;
    }

    @Override
    public String toString(){
	try{
	    return ("/Entities.Event{ID:"+this.getPID()+", Dept_ID:\""+this.getDepartment().getPID()+"\", Department:\""+this.getDepartment().getName()+"\", Venue_ID:\""+this.getVenue().getPID()+"\", Venue:\""+this.getVenue().getTitle()+"\", Title:\""+this.getTitle()+"\", Description:{Length:"+((this.getDescription()==null) ? 0 : this.getDescription().length())+"}, EBegin:\""+this.getEBegin()+"\", EEnd:\""+this.getEEnd()+"\", Comments:"+this.getComments().size()+", State:"+this.getAState().toUpperCase()+", Create_Date:\""+this.getCDate()+"\", Last_Modified:\""+this.getMDate()+"\"}");
	}catch(Exception ex){
	    return ex.toString();
	}
    }
}

src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/entities/Venue.java
package edu.iit.sat.itmd4515.abhimani.fp.domain.entities;

import edu.iit.sat.itmd4515.abhimani.fp.domain.AbstractEntityUnit;
import edu.iit.sat.itmd4515.abhimani.fp.domain.Venue_Type;
import edu.iit.sat.itmd4515.abhimani.fp.US_States;
import java.io.Serializable;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
@Entity
@Table(name = "venues")
@NamedQueries({
    @NamedQuery(name = "Venues.retrieveAll", query = "SELECT v FROM Venue AS v"),
    @NamedQuery(name = "Venues.findByID", query = "SELECT v FROM Venue AS v WHERE v.PID=:PID"),
    @NamedQuery(name = "Venues.findByName", query = "SELECT v FROM Venue As v WHERE v.Title=:Name")
})
public class Venue
	extends AbstractEntityUnit
	implements Comparable<Venue>, Serializable{
    //COLUMNS
    @Column(name = "Title", nullable = false, length = 255, unique = true)
    @Size(min = 4)
    private String Title;

    @Column(name = "Type", nullable = false)
    private Venue_Type Type=Venue_Type.Open;

    @Column(name = "Addr1", nullable = false, length = 255)
    @Size(min = 6)
    private String Addr1;

    @Column(name = "Addr2", length = 255)
    private String Addr2;

    @Column(name = "City", nullable = false, length = 255)
    @Size(min = 3)
    private String City;

    @Column(name = "CState", nullable = false, length = 255)
    private US_States CState;

    @Column(name = "Zip", nullable = false, length = 5)
    @Min(1000)
    @Max(99999)
    private int Zip;

    @Column(name = "Zip_Ext", length = 4)
    @Min(100)
    @Max(9999)
    private int Zip_Ext=0;

    @OneToMany(cascade = CascadeType.PERSIST, mappedBy = "Ven")
    private List<Event> lstEvents;

    //CONSTRUCTS
    public Venue(){
	super();
    }

    public Venue(String Title, Venue_Type Type, String Addr1, String Addr2, String City, US_States CState, int Zip, int Zip_Ext){
	this.Title=Title.trim();
	this.Type=Type;
	this.Addr1=Addr1.trim();
	this.Addr2=Addr2.trim();
	this.City=City.trim();
	this.CState=CState;
	this.Zip=Zip;
	this.Zip_Ext=Zip_Ext;
    }

    public Venue(String Title, Venue_Type Type, String Addr1, String City, US_States CState, int Zip){
	this.Title=Title.trim();
	this.Type=Type;
	this.Addr1=Addr1.trim();
	this.City=City.trim();
	this.CState=CState;
	this.Zip=Zip;
    }

    //PROPERTIES
    public String getTitle(){
	return Title;
    }

    public void setTitle(String Title){
	this.Title=Title.trim();
    }

    public String getType(){
	return Type.toString();
    }

    public void setType(Venue_Type Type){
	this.Type=Type;
    }

    public String getAddr1(){
	return Addr1;
    }

    public void setAddr1(String Addr1){
	this.Addr1=Addr1.trim();
    }

    public String getAddr2(){
	return Addr2;
    }

    public void setAddr2(String Addr2){
	this.Addr2=Addr2.trim();
    }

    public String getCity(){
	return City;
    }

    public void setCity(String City){
	this.City=City.trim();
    }

    public String getCState(){
	return CState.toString();
    }

    public void setCState(US_States CState){
	this.CState=CState;
    }

    public int getRawZip(){
	return this.Zip;
    }

    public String getZip(){
	return ((this.Zip_Ext>0) ? (Zip+"-"+Zip_Ext) : Integer.toString(Zip));
    }

    public void setZip(int Zip){
	this.Zip=Zip;
    }

    public int getZip_Ext(){
	return Zip_Ext;
    }

    public void setZip_Ext(int Ext){
	this.Zip_Ext=Ext;
    }

    //RELATIONS
    /**
     * To hold a list of events that are held or will be held at the venue.
     *
     * @return Returns a list of Events held at the Venue
     */
    public List<Event> getVenueEvents(){
	return lstEvents;
    }

    //IMPLEMENTATION
    /**
     * CompareTo implemented on the Title field which is unique.
     *
     * @param el Expects an element of type Venue
     */
    @Override
    public int compareTo(Venue el){
	return (this.getTitle().compareTo(el.getTitle()));
    }

    //OVERRIDES
    @Override
    public boolean equals(Object el){
	if(!(el instanceof Venue))
	    return false;
	try{
	    Venue tstVenue=(Venue)el;
	    if(!(Integer.compare(this.hashCode(), tstVenue.hashCode())==0))
		return false;
	}catch(Exception ex){
	    return false;
	}
	return true;
    }

    @Override
    public String toString(){
	try{
	    return ("/Entities.Venue{ID:"+this.getPID()+", Title:\""+this.getTitle()+"\", Type:\""+this.getType()+"\", Address:{Addr1:\""+this.getAddr1()+"\", Addr2:\""+((this.getAddr2()==null) ? "" : this.getAddr2())+"\", City:\""+this.getCity()+"\", State:"+this.getCState()+", Zip:"+this.getZip()+"}}");
	}catch(Exception ex){
	    return ex.toString();
	}
    }
}

src/main/webapp/Students/Event.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		    xmlns:h="http://java.sun.com/jsf/html"
		    xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
		    xmlns:f="http://java.sun.com/jsf/core"
		    xmlns:o="http://omnifaces.org/ui"
		    xmlns:of="http://omnifaces.org/functions"
		    template="./../WEB-INF/abstracts/tplStudents2.xhtml">
<ui:define name="cph_Title">Event - #{controllerEventData.currentEvent.title}</ui:define>


<ui:define name="cph_Heading"><span id="lblHeading">#{controllerEventData.currentEvent.title}</span></ui:define>


<ui:define name="cph_Content">
<h:form id="x0">
    <f:metadata>
	<f:viewParam name="event_id" value="#{controllerEventData.event_id}" />
	<f:viewAction action="#{controllerEventData.pre_load}" />
    </f:metadata>
<table id="tblx">
<tbody>
    <tr><td style="border-top:1px solid #bbb;">#{event_id}</td></tr>
    <tr>
	<td><h:outputLink value="Events.xhtml">&#8678; Back to Events</h:outputLink>
	</td>
    </tr>
     <tr>
	<td><label>
	    <span class="bold">Description</span><br />
	    <h:outputText value="#{empty controllerEventData.currentEvent.description? '-': controllerEventData.currentEvent.description}"></h:outputText>
	    </label>
	</td>
    </tr>
    <tr>
	<td><label>
	    <span class="bold">Date Posted</span><br />
	    <h:outputText value="#{controllerEventData.currentEvent.CDate}"></h:outputText>
	    </label>
	</td>
    </tr>
      <tr>
	<td><label>
	    <span class="bold">Begin Date/Time</span><br />
	    <h:outputText value="#{controllerEventData.currentEvent.EBegin}"></h:outputText>
	    </label>
	</td>
    </tr>
     <tr>
	<td><label>
	    <span class="bold">End Date/Time</span><br />
	    <h:outputText value="#{controllerEventData.currentEvent.EEnd}"></h:outputText>
	    </label>
	</td>
    </tr>
    <tr>
	<td><label>
	    <span class="bold">Venue</span><br />
	    <h:outputLabel value="#{controllerEventData.currentEvent.venue.title}">,</h:outputLabel>
	    <h:outputLabel value="#{controllerEventData.currentEvent.venue.addr1}">,</h:outputLabel>
	    <h:outputLabel rendered="#{not empty controllerEventData.currentEvent.venue.addr2}" value="#{controllerEventData.currentEvent.venue.addr2}">,</h:outputLabel>
	    <h:outputLabel value="#{controllerEventData.currentEvent.venue.city}, #{controllerEventData.currentEvent.venue.CState}">,</h:outputLabel>
	    <h:outputLabel value="#{controllerEventData.currentEvent.venue.zip}">.</h:outputLabel>
	    </label>
	</td>
    </tr>
     <tr>
	<td><label>
	    <span class="bold">Students attending the Event</span><br />
	    <ui:repeat value="#{controllerEventData.currentEvent.studentList}" var="student">
		<span>#{student.FName} #{student.FName} (#{student.auth.username})</span><br />
	    </ui:repeat>
	    <span class="bold">Total</span><h:outputText value=" #{controllerEventData.currentEvent.studentList.size()}"></h:outputText>
	    </label>
	</td>
    </tr>
    <tr>
	<td><label>
	    <span class="bold">Are you attending?</span><br />
	    <h:selectBooleanCheckbox accesskey="#{controllerEventData.currentEvent.PID}" disabled="#{not controllerEventData.isNotPast}" id='chkIsGoing' value="#{controllerEventData.isAttendingEvent}"></h:selectBooleanCheckbox> <h:outputLabel style="display:inline;" class="red" rendered="#{not controllerEventData.isNotPast}"> This event is alreay past.</h:outputLabel>
	    </label>
	</td>
    </tr>
    <tr>
	<td><h:outputLink value="Events.xhtml">&#8678; Back to Events</h:outputLink>
	</td>
    </tr>
    <tr><td style="border-bottom:1px solid #bbb;"></td></tr>
    <tr><td><br /></td></tr>
    <tr><td style="border-bottom:1px solid #bbb;"></td></tr>
    <tr>
    <td style="border-bottom:1px solid #bbb;">
	<span class="bold">Comments</span>
    </td>
    </tr>
    <tr><td>
	     <ui:repeat value="#{controllerEventData.currentEvent.comments}" var="comment">
		 <span class="bold">#{comment.student.FName}</span> <span>#{comment.comment}</span><br />
	    </ui:repeat>
	</td></tr>
     <tr>
	<td><label>
	    <span class="bold">Comment</span> <span class="red">*</span><br />
	    <h:inputTextarea p:placeholder="Enter Comment" id="txtComment" value="#{controllerEventData.newComment}"></h:inputTextarea>
	    </label>
	</td>
    </tr>
    <tr><td style="color:#bbb;">
	    <h:commandButton id='btnComment' action="#{controllerEventData.addComment()}" value="post" style="margin-left:0;padding-left:0;" />
	</td>
    </tr>
</tbody>
</table>
</h:form> 
</ui:define>

<ui:define name="cph_PostLoadScripts">
<h:outputScript>//<![CDATA[
var x=document.forms[0];
try{fncFrmLoad(x);
    var validate=function(x){
	var t=true;
	    if(t){
		var y=$(document.getElementById('x0:txtComment'));
		if((y.val()).length<2){
		    y.focus();
		    y.addClass('redline');
		    t=false;
		}else y.removeClass('redline');
	    }
	    return t;
	};
    (document.getElementById('x0:btnComment')).onclick=function(){
	var t=validate(this);
	if(!t) return false;
	//if(t) x.submit();
	//return false;
    };
}catch(e){alert(e);}
$(document).ready(function(){
			if($(document.getElementById('lblHeading')).text()=='') window.location='Events.xhtml?msg=The_system_could_not_find_the_event.';
			
			$(document.getElementById('x0:chkIsGoing')).change(function(){
									$.get('ajax/register_for_event?id='+ $(this).attr('accesskey'));
									    });
		    });
//]]></h:outputScript>
</ui:define>
</ui:composition>

src/main/webapp/Students/index.xhtml
<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta http-equiv="REFRESH" content="0; Events.xhtml" />
</head>
</html>