src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/Venue_Type.java
package edu.iit.sat.itmd4515.abhimani.fp.domain;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
public enum Venue_Type{
    Open, Hall, Class, Room, Exhibition
}

src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/authorization/StudentLogin.java
package edu.iit.sat.itmd4515.abhimani.fp.domain.authorization;

import edu.iit.sat.itmd4515.abhimani.fp.EncryptText;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
@Entity
@Table(name="auth_students_login")
@NamedQueries({
    @NamedQuery(name="StudentLogin.authenticate", query="SELECT l FROM StudentLogin AS l WHERE l.Username=:uname AND l.Password IS NOT NULL")
})
public class StudentLogin
	implements Comparable<StudentLogin>, Serializable{
    //COLUMNS
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(nullable=false)
    protected long LoginID;

    @Column(length=255, unique=true, updatable=false)
    @Size(min=4)
    private String Username;

    @Column(name="enc_pwd", length=64)
    @Size(min=8, max=40)
    private String Password;

    //CONSTRUCT
    private StudentLogin(){
	super();
    }

    /**
     * You must not initialize and use an instance of this class with the
     * default constructor, instead use the Student.getAuth() and
     * Student.setAuth(StudentLogin auth) methods to access or update the
     * credentials; Use this constructor only to use the matchLogin(String
     * Password) and authenticate the user.
     *
     * @param Username Expects a Username to initialize the class
     */
    public StudentLogin(String Username){
	this.Username=Username.trim();
    }

    //PROPERTIES
    public long getLoginID(){
	return this.LoginID;
    }

    public String getUsername(){
	return this.Username;
    }

    public String getPasswordKey(){
	return this.Password;
    }

    /**
     * Password is sha256ed and saved.
     *
     */
    @PrePersist
    @PreUpdate
    private void cryptPassword(){
	this.Password=EncryptText.crypt(this.Password);
    }

    public void setPassword(String Password){
	this.Password=Password.trim();
    }

    /**
     * Can be used to authenticate the user.
     *
     *
     * @param Password Expects Student password for matching
     *
     * @return A Boolean True or False
     */
    public boolean matchLogin(String Password){
	return EncryptText.hashEquals(this.getPasswordKey(), Password);
    }

    //IMPLEMENTATION
    /**
     * CompareTo implemented on the Username of the Student which is unqiue.
     *
     * @param el Expects an element of type StudentLogin
     */
    @Override
    public int compareTo(StudentLogin el){
	return (this.getUsername().compareTo(el.getUsername()));
    }

    //OVERRIDES
    @Override
    public int hashCode(){
	return ((this.getLoginID()>0) ? Long.hashCode(this.getLoginID()) : 0);
    }

    @Override
    public boolean equals(Object el){
	if(!(el instanceof StudentLogin))
	    return false;
	try{
	    StudentLogin tstLogin=(StudentLogin)el;
	    if(!(Integer.compare(this.hashCode(), tstLogin.hashCode())==0))
		return false;
	}catch(Exception ex){
	    return false;
	}
	return true;
    }

    @Override
    public String toString(){
	try{
	    return ("NOT_AUTHORIZED");
	}catch(Exception ex){
	    return ex.toString();
	}
    }
}

src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/entities/Event.java
package edu.iit.sat.itmd4515.abhimani.fp.domain.entities;

import edu.iit.sat.itmd4515.abhimani.fp.domain.AbstractEntityUnit;
import edu.iit.sat.itmd4515.abhimani.fp.domain.EventState;
import edu.iit.sat.itmd4515.abhimani.fp.domain.relations.Comment;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Future;
import javax.validation.constraints.Size;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
@Entity
@Table(name = "event_store")
@NamedQueries({
    @NamedQuery(name = "Events.retrieveAll", query = "SELECT e FROM Event AS e"),
    @NamedQuery(name = "Events.findByID", query = "SELECT e FROM Event AS e WHERE e.PID=:PID"),
    @NamedQuery(name = "Events.retrieveByDepartment", query = "SELECT e FROM Event AS e WHERE e.Dept=:Dept"),
    @NamedQuery(name = "Events.retrieveByVenue", query = "SELECT e FROM Event AS e WHERE e.Ven=:Ven")
})
public class Event
	extends AbstractEntityUnit
	implements Comparable<Event>, Serializable{
    //COLUMNS
    @Column(name = "Title", nullable = false, length = 255, unique = true)
    @Size(min = 4)
    private String Title;

    @Column(name = "Description", length = 2000)
    private String Description;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EBegin", nullable = false)
    @Future
    private Date EBegin;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EEnd", nullable = false)
    @Future
    private Date EEnd;

    @Column(name = "AState", nullable = false)
    private EventState AState=EventState.NEW;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CDate", nullable = false, insertable = true, updatable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private final Date CDate=new Date();

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MDate", insertable = false, updatable = true, columnDefinition = "TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
    private Date MDate;

    @JoinColumn(name = "Event_Dept_ID", referencedColumnName = "PID", nullable = false)
    @ManyToOne(optional = false)
    private Department Dept;

    @JoinColumn(name = "Event_Venue_ID", referencedColumnName = "PID", nullable = false)
    @ManyToOne(optional = false)
    private Venue Ven;

    @OneToMany(cascade = CascadeType.REMOVE, mappedBy = "Evt")
    private List<Comment> lstComments;

    @ManyToMany(mappedBy = "lstEvents")
    private List<Student> lstStudents=new ArrayList<>();

    //CONSTRUCTS
    public Event(){
	super();
    }

    public Event(Department Dept, Venue Ven, String Title, String Description, Date EBegin, Date EEnd, EventState AState){
	this.Dept=Dept;
	this.Ven=Ven;
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
	this.AState=AState;
    }

    public Event(Department Dept, Venue Ven, String Title, String Description, Date EBegin, Date EEnd){
	this.Dept=Dept;
	this.Ven=Ven;
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
    }

    public Event(String Title, String Description, Date EBegin, Date EEnd, EventState AState){
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
	this.AState=AState;
    }

    public Event(String Title, String Description, Date EBegin, Date EEnd){
	this.Title=Title.trim();
	this.Description=Description.trim();
	this.EBegin=EBegin;
	this.EEnd=EEnd;
    }

    //PROPERTIES
    public String getTitle(){
	return Title;
    }

    public void setTitle(String Title){
	this.Title=Title.trim();
    }

    public String getDescription(){
	return Description;
    }

    public void setDescription(String Description){
	this.Description=Description.trim();
    }

    public Date getRawEBegin(){
	return EBegin;
    }

    public String getEBegin(){
	return EBegin.toString();
    }

    public void setEBegin(Date EBegin){
	this.EBegin=EBegin;
    }

    public Date getRawEEnd(){
	return EEnd;
    }

    public String getEEnd(){
	return EEnd.toString();
    }

    public void setEEnd(Date EEnd){
	this.EEnd=EEnd;
    }

    public EventState getRawAState(){
	return AState;
    }

    public String getAState(){
	return AState.toString();
    }

    public void setAState(EventState AState){
	this.AState=AState;
    }

    /**
     * This field is inserted only once automatically upon row creation.
     *
     * @return Returns Creation Date
     */
    public String getCDate(){
	return CDate.toString();
    }

    /**
     * This field is updated automatically receives last update date.
     *
     * @return Returns Last Modified Date
     */
    public String getMDate(){
	return ((MDate==null) ? "-" : MDate.toString());
    }

    //RELATIONS
    public Department getDepartment(){
	return Dept;
    }

    public void setDepartment(Department Dept){
	this.Dept=Dept;
    }

    public Venue getVenue(){
	return Ven;
    }

    public void setVenue(Venue Ven){
	this.Ven=Ven;
    }

    public List<Student> getStudentList(){
	return lstStudents;
    }

    public void addStudent(Student stud){
	if(!this.getStudentList().contains(stud))
	    this.lstStudents.add(stud);
	if(!stud.getEventList().contains(this))
	    stud.attendEvent(this);
    }

    public void removeStudent(Student stud){
	if(this.getStudentList().contains(stud))
	    this.lstStudents.remove(stud);
	if(stud.getEventList().contains(this))
	    stud.unAttendEvent(this);
    }

    /**
     * Holds a list of comments received for the event.
     *
     * @return Returns a list of Comments from Students for the Event
     */
    public List<Comment> getComments(){
	return lstComments;
    }

    //IMPLEMENTATION
    /**
     * CompareTo implemented on the Title field.
     *
     * @param el Expects an element of type Event
     */
    @Override
    public int compareTo(Event el){
	return (this.getEBegin().compareTo(el.getEBegin()));
    }

    //OVERRIDES
    @Override
    public boolean equals(Object el){
	if(!(el instanceof Event))
	    return false;
	try{
	    Event tstEvt=(Event)el;
	    if(!(Integer.compare(this.hashCode(), tstEvt.hashCode())==0))
		return false;
	}catch(Exception ex){
	    return false;
	}
	return true;
    }

    @Override
    public String toString(){
	try{
	    return ("/Entities.Event{ID:"+this.getPID()+", Dept_ID:\""+this.getDepartment().getPID()+"\", Department:\""+this.getDepartment().getName()+"\", Venue_ID:\""+this.getVenue().getPID()+"\", Venue:\""+this.getVenue().getTitle()+"\", Title:\""+this.getTitle()+"\", Description:{Length:"+((this.getDescription()==null) ? 0 : this.getDescription().length())+"}, EBegin:\""+this.getEBegin()+"\", EEnd:\""+this.getEEnd()+"\", Comments:"+this.getComments().size()+", State:"+this.getAState().toUpperCase()+", Create_Date:\""+this.getCDate()+"\", Last_Modified:\""+this.getMDate()+"\"}");
	}catch(Exception ex){
	    return ex.toString();
	}
    }
}

src/main/java/edu/iit/sat/itmd4515/abhimani/fp/domain/entities/Venue.java
package edu.iit.sat.itmd4515.abhimani.fp.domain.entities;

import edu.iit.sat.itmd4515.abhimani.fp.domain.AbstractEntityUnit;
import edu.iit.sat.itmd4515.abhimani.fp.domain.Venue_Type;
import edu.iit.sat.itmd4515.abhimani.fp.US_States;
import java.io.Serializable;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.fp
 */
@Entity
@Table(name = "venues")
@NamedQueries({
    @NamedQuery(name = "Venues.retrieveAll", query = "SELECT v FROM Venue AS v"),
    @NamedQuery(name = "Venues.findByID", query = "SELECT v FROM Venue AS v WHERE v.PID=:PID"),
    @NamedQuery(name = "Venues.findByName", query = "SELECT v FROM Venue As v WHERE v.Title=:Name")
})
public class Venue
	extends AbstractEntityUnit
	implements Comparable<Venue>, Serializable{
    //COLUMNS
    @Column(name = "Title", nullable = false, length = 255, unique = true)
    @Size(min = 4)
    private String Title;

    @Column(name = "Type", nullable = false)
    private Venue_Type Type=Venue_Type.Open;

    @Column(name = "Addr1", nullable = false, length = 255)
    @Size(min = 6)
    private String Addr1;

    @Column(name = "Addr2", length = 255)
    private String Addr2;

    @Column(name = "City", nullable = false, length = 255)
    @Size(min = 3)
    private String City;

    @Column(name = "CState", nullable = false, length = 255)
    private US_States CState;

    @Column(name = "Zip", nullable = false, length = 5)
    @Min(1000)
    @Max(99999)
    private int Zip;

    @Column(name = "Zip_Ext", length = 4)
    @Min(100)
    @Max(9999)
    private int Zip_Ext=0;

    @OneToMany(cascade = CascadeType.PERSIST, mappedBy = "Ven")
    private List<Event> lstEvents;

    //CONSTRUCTS
    public Venue(){
	super();
    }

    public Venue(String Title, Venue_Type Type, String Addr1, String Addr2, String City, US_States CState, int Zip, int Zip_Ext){
	this.Title=Title.trim();
	this.Type=Type;
	this.Addr1=Addr1.trim();
	this.Addr2=Addr2.trim();
	this.City=City.trim();
	this.CState=CState;
	this.Zip=Zip;
	this.Zip_Ext=Zip_Ext;
    }

    public Venue(String Title, Venue_Type Type, String Addr1, String City, US_States CState, int Zip){
	this.Title=Title.trim();
	this.Type=Type;
	this.Addr1=Addr1.trim();
	this.City=City.trim();
	this.CState=CState;
	this.Zip=Zip;
    }

    //PROPERTIES
    public String getTitle(){
	return Title;
    }

    public void setTitle(String Title){
	this.Title=Title.trim();
    }

    public String getType(){
	return Type.toString();
    }

    public void setType(Venue_Type Type){
	this.Type=Type;
    }

    public String getAddr1(){
	return Addr1;
    }

    public void setAddr1(String Addr1){
	this.Addr1=Addr1.trim();
    }

    public String getAddr2(){
	return Addr2;
    }

    public void setAddr2(String Addr2){
	this.Addr2=Addr2.trim();
    }

    public String getCity(){
	return City;
    }

    public void setCity(String City){
	this.City=City.trim();
    }

    public String getCState(){
	return CState.toString();
    }

    public void setCState(US_States CState){
	this.CState=CState;
    }

    public int getRawZip(){
	return this.Zip;
    }

    public String getZip(){
	return ((this.Zip_Ext>0) ? (Zip+"-"+Zip_Ext) : Integer.toString(Zip));
    }

    public void setZip(int Zip){
	this.Zip=Zip;
    }

    public int getZip_Ext(){
	return Zip_Ext;
    }

    public void setZip_Ext(int Ext){
	this.Zip_Ext=Ext;
    }

    //RELATIONS
    /**
     * To hold a list of events that are held or will be held at the venue.
     *
     * @return Returns a list of Events held at the Venue
     */
    public List<Event> getVenueEvents(){
	return lstEvents;
    }

    //IMPLEMENTATION
    /**
     * CompareTo implemented on the Title field which is unique.
     *
     * @param el Expects an element of type Venue
     */
    @Override
    public int compareTo(Venue el){
	return (this.getTitle().compareTo(el.getTitle()));
    }

    //OVERRIDES
    @Override
    public boolean equals(Object el){
	if(!(el instanceof Venue))
	    return false;
	try{
	    Venue tstVenue=(Venue)el;
	    if(!(Integer.compare(this.hashCode(), tstVenue.hashCode())==0))
		return false;
	}catch(Exception ex){
	    return false;
	}
	return true;
    }

    @Override
    public String toString(){
	try{
	    return ("/Entities.Venue{ID:"+this.getPID()+", Title:\""+this.getTitle()+"\", Type:\""+this.getType()+"\", Address:{Addr1:\""+this.getAddr1()+"\", Addr2:\""+((this.getAddr2()==null) ? "" : this.getAddr2())+"\", City:\""+this.getCity()+"\", State:"+this.getCState()+", Zip:"+this.getZip()+"}}");
	}catch(Exception ex){
	    return ex.toString();
	}
    }
}

src/main/webapp/Administrators/Venues/Manage_Venue.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		   xmlns:h="http://java.sun.com/jsf/html"
		   xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
		   xmlns:f="http://java.sun.com/jsf/core"
		    template="./../../WEB-INF/abstracts/tplAdmin2.xhtml">
<ui:define name="cph_Title">New Venue</ui:define>

<ui:define name="cph_Heading">#{empty request.getParameter("venue_id")? 'Create': 'Update'} Venue</ui:define>

<ui:define name="cph_Content">
<h:form id="x0">
    <f:metadata>
	<f:viewParam name="venue_id" value="#{controllerProcessVenue.venue_id}" />
	<f:viewAction action="#{controllerProcessVenue.pre_load}" />
    </f:metadata>
<table id="tblx">
<tbody>
    <tr><td style="border-top:1px solid #bbb;"></td></tr>
     <tr>
	<td><label>
	    <span class="bold">Title</span> <span class="red">*</span><br />
	     <h:inputText id="txtTitle" title="Enter Title" p:placeholder="Enter Title" maxlength="155" alt="1" value="#{controllerProcessVenue.strTitle}" />
	    </label>
	</td>
    </tr>
    <tr>
	<td><label>
	    <span class="bold">Address</span> <span class="red">*</span><br />
	     <h:inputText id="txtAddr1" title="Enter Address 1" p:placeholder="Enter Address 1" maxlength="155" alt="1" value="#{controllerProcessVenue.strAddr1}" /><br /><br />
	     <h:inputText id="txtAddr2" title="Enter Address 2" p:placeholder="Enter Address 2" maxlength="155" value="#{controllerProcessVenue.strAddr2}" /><br /><br />
	     <h:inputText id="txtCity" title="Enter City" p:placeholder="Enter City" maxlength="155" size="3" alt="1" value="#{controllerProcessVenue.strCity}" /><br /><br />
	     <h:inputText id="txtZip" title="Enter Zip" p:placeholder="Enter Zip" maxlength="5" alt="7" value="#{controllerProcessVenue.strZip}" /><br /><br />
	     <h:inputText id="txtZipExt" title="Enter Zip Ext" p:placeholder="Enter Zip Ext" maxlength="4" alt="numeric" value="#{controllerProcessVenue.strZipExt}" /><br />
	    </label>
	</td>
    </tr>
    <tr><td style="border-bottom:1px solid #bbb;"></td></tr>
    <tr><input name="frmChk" type="hidden" value="0" />
	<td style="color:#bbb;">
	    <h:commandButton action="#{controllerProcessVenue.manipulateVenue()}" value="save" style="margin-left:0;padding-left:0;" /> | <input type="reset" id="reset" value="clear" />
	</td>
    </tr>
</tbody>
</table>
</h:form>  
</ui:define>

<ui:define name="cph_PostLoadScripts">
<h:outputScript>//<![CDATA[
var x=document.forms[0];
try{fncFrmLoad(x);
    var validate=function(x){
	var t=fncValidateFrm(x);
	    if(t){
		
	    }
	    return t;
	};
    x.onsubmit=function(){
	var t=validate(this);
	if(!t) return false;
	//if(t) x.submit();
	//return false;
    };
}catch(e){alert(e);}
$(document).ready(function(){
   
});
//]]></h:outputScript>
</ui:define>
</ui:composition>

src/main/webapp/Administrators/Venues/Welcome.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		    xmlns:h="http://java.sun.com/jsf/html"
		    template="./../../WEB-INF/abstracts/tplAdmin2.xhtml">
<ui:define name="cph_Title">Welcome</ui:define>


<ui:define name="cph_PageStyles">
<style type="text/css" media="all">
ul.event_tab.menu{width:29%;}
</style>
</ui:define>


<ui:define name="cph_Heading">Dashboard</ui:define>


<ui:define name="cph_Content">
<ul id="updateList1" class="event_tab menu nav">
<li class="heading">Venues</li>
<ui:repeat value="#{controllerFetchVenues.lstVenues}" var="venue">
<li>
    <span class="attribute">
	<a title="Edit" href="Manage_Venue.xhtml?venue_id=#{venue.ID}" class="title">#{venue.title}</a>
	<a title="Edit" href="Manage_Venue.xhtml?venue_id=#{venue.ID}" class="action right text-right"><img style="cursor:pointer;border:0 none;" src="/res/img.icon.edit.png" title="Edit" alt="edit" /></a>
    </span>
    <span class="attribute"><span class="bold">Address : </span> 
	<h:outputLabel value="#{venue.addr1}">,</h:outputLabel>
	<h:outputLabel rendered="#{not empty venue.addr2}" value="#{venue.addr2}">,</h:outputLabel>
	<h:outputLabel value="#{venue.city}, #{venue.CState}">,</h:outputLabel>
	<h:outputLabel value="#{venue.zip}">.</h:outputLabel>
    </span>
    <span class="attribute"><span class="bold">No of Events at the Venue : </span> <h:outputText value="#{venue.venueEvents.size()}"/></span>
</li>
</ui:repeat>
<li></li>
<li class="right"><a href="Manage_Venue.xhtml">Add New</a></li>
</ul>

<ul id="updateList2" class="event_tab menu nav">
<li class="heading">Events Pending Approval</li>
<ui:repeat value="#{controllerFetchVenues.lstPendingEvents}" var="event">
<li>
    <span class="attribute">
	<a href="#" class="title">#{event.title}</a>
	<h:outputText value="#{event.description}"/>
    </span>
    <span class="attribute"><span class="bold">Begin : </span> <h:outputText value="#{event.EBegin}"/></span>
    <span class="attribute"><span class="bold">End : </span> <h:outputText value="#{event.EEnd}"/></span>
    <span class="attribute"><span class="bold">Held by : </span> <h:outputText value="#{event.department.name}"/></span>
    <span class="attribute"><span class="bold">Held at : </span> <h:outputText value="#{event.venue.title}"/></span>
    <span class="attribute">
    <span class="bold">Total</span><h:outputText value=" #{event.studentList.size()}"></h:outputText>
    </span>
    <span class="attribute"><span class="bold">Approve? : </span> <h:selectBooleanCheckbox accesskey="#{event.PID}" class='chkIsApproved' value="false"></h:selectBooleanCheckbox></span>
</li>
</ui:repeat>
</ul>
    
<ul id="updateList3" class="event_tab menu nav">
<li class="heading">Events Approved</li>
<ui:repeat value="#{controllerFetchVenues.lstActiveEvents}" var="event">
<li>
    <span class="attribute">
	<a href="#" class="title">#{event.title}</a>
	<h:outputText value="#{event.description}"/>
    </span>
    <span class="attribute"><span class="bold">Begin : </span> <h:outputText value="#{event.EBegin}"/></span>
    <span class="attribute"><span class="bold">End : </span> <h:outputText value="#{event.EEnd}"/></span>
    <span class="attribute"><span class="bold">Held by : </span> <h:outputText value="#{event.department.name}"/></span>
    <span class="attribute"><span class="bold">Held at : </span> <h:outputText value="#{event.venue.title}"/></span>
    <span class="attribute">
    <span class="bold">Students attending the Event : </span><br />
    <ui:repeat value="#{event.studentList}" var="student">
	<span>#{student.FName} #{student.FName} (#{student.auth.username})</span><br />
    </ui:repeat>
    <span class="bold">Total</span><h:outputText value=" #{event.studentList.size()}"></h:outputText>
    </span>
    <span class="attribute"><span class="bold">No. of Comments : </span> <h:outputText value="#{event.comments.size()}"/></span>
</li>
</ui:repeat>
</ul>
</ui:define>

<ui:define name="cph_PostLoadScripts">
<h:outputScript>//<![CDATA[
$(document).ready(function(){
var refreshPanels=function(){
	$('ul.event_tab.menu').each(function(){
	     $(this).show(0);
	     if($(this).children('li').length==1) $(this).hide(0);
	});
    }
    $(document).on('click', 'input.chkIsApproved', function(){
			    $.get('ajax/approve_event?id='+ $(this).attr('accesskey'), function(){
								$('ul#updateList2').load('Welcome.xhtml #updateList2 li',
								    function(){
									$('ul#updateList3').load('Welcome.xhtml #updateList3 li', function(){
									    refreshPanels();
									    });
									});
							});
				});
	    refreshPanels();
	});
//]]></h:outputScript>
</ui:define>
</ui:composition>

src/main/webapp/Administrators/Venues/index.xhtml
<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta http-equiv="REFRESH" content="0; Welcome.xhtml" />
</head>
</html>